@startuml
'https://plantuml.com/class-diagram

abstract class Unit
class Resume {
-String uuid
-String fullName
-Map<ContactsTypes, String> contacts
-Map<UnitTypes, Unit> unit
}

class Content {
    - Link link;
    - LocalDate dateOfStart;
    - LocalDate dateOfEnd;
    - String position;
    - String desc;
}

class TextUnit {
-String text
}
class ContentUnit {
-List<Content> content
}
class ListUnit {
-List<String> items
}

TextUnit --> Unit
ContentUnit *----> Unit
ListUnit --> Unit
Resume *----> Unit
ContentUnit --> Content

@enduml